<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.10.1 on win32)" generated="20220111 02:37:36.361" rpa="false" schemaversion="2">
<suite id="s1" name="Lanuch" source="C:\Users\Ankit Yadav\PycharmProjects\Testing\TestCase\Lanuch.robot">
<test id="s1-t1" name="Open The Web">
<kw name="Lunch The Url">
<msg timestamp="20220111 02:37:36.408" level="FAIL">No keyword with name 'Lunch The Url' found.</msg>
<status status="FAIL" starttime="20220111 02:37:36.408" endtime="20220111 02:37:36.423"/>
</kw>
<status status="FAIL" starttime="20220111 02:37:36.408" endtime="20220111 02:37:36.423">No keyword with name 'Lunch The Url' found.</status>
</test>
<status status="FAIL" starttime="20220111 02:37:36.361" endtime="20220111 02:37:36.423"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Lanuch">Lanuch</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220111 02:37:36.408" level="ERROR">Error in file 'C:\Users\Ankit Yadav\PycharmProjects\Testing\TestCase\Lanuch.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\Ankit Yadav\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  C:\Users\Ankit Yadav\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\Ankit Yadav\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\Ankit Yadav\AppData\Local\Programs\Python\Python310\lib
  C:\Users\Ankit Yadav\AppData\Local\Programs\Python\Python310
  C:\Users\Ankit Yadav\AppData\Local\Programs\Python\Python310\lib\site-packages</msg>
<msg timestamp="20220111 02:37:36.408" level="ERROR">Error in file 'C:\Users\Ankit Yadav\PycharmProjects\Testing\TestCase\Lanuch.robot' on line 3: Resource file 'C:\Users\Ankit Yadav\PycharmProjects\Testing\TestCase\Keyword\Function.robot' does not exist.</msg>
</errors>
</robot>
